### ISSUE TITLE
Avoid using the connection pool and instead, create the connection just-in-time, when it is required (with GCP - Cloud functions)

### ISSUE THREAD

**Issue by bbbouvier** [VilledeMontreal/express-idempotency-mongo-adapter#11]
First of all thank you very much for this library which is really helpful, I am using it and it works perfectly.

Although I integrated it within some specific routes of my api located under a Google Cloud Function, and it create many extras connection to the database even though the specific routes are not called.

How could we create create the database connection just-in-time (only when routes configured with idempotency service get called) ?

Thanks in advance for your recommandations.

**Comment by joscelynjean** [comment]
Hi @rodneyrd  ,

Thank you for your kind words.

I think the functionality that will suit you best is the use of the adapter delegate function. But I need to adjust the behavior so the adapter calls the delegate function everytime it requires database connectivity instead of keeping the reference. I should also introduce some callback function which will allow you to close the connection when the adapter is done using it.
 
I will let you know when I adjust the code and a release candidate is available so you can do some testing on your side.

**Comment by bbbouvier** [comment]
Hi @joscelynjean,

As soon as you are ready I'll be do the testing. 
Feel free to let me know when I can try it out.

**Comment by joscelynjean** [comment]
Hi @rodneyrd ,

Got some problems with CircleCI but now is all goods. You can test [v1.0.4-rc.2](https://www.npmjs.com/package/express-idempotency-mongo-adapter/v/1.0.4-rc.2), which is a release candidate.

Basically, when you will initialize the adapter, is will be important to use the 3 following options : 

```
...
useDelegation: true,
delegate: your function which provide a Mongo.Db reference (ex: MongoClient.connect().Db()),
onAfterDbUse: provide a function to close your connection (ex: MongoClient.close() ),
...
```

I have not tested it well for now, I wanted to unblock yourself but I will provide unit tests and a Docker example of what you are trying to achieve.

Just let me know how it is going!

Thank you

**Comment by bbbouvier** [comment]
Hi @joscelynjean thank you very much for this. Sorry for the delay, it took me quite some time to investigate and find a solution as it didn't really solve my issue since it is more a context related issue.
The adapter was still calling the DB connection at every cloud runtime execution because I instantiated the mongo adapter (`newAdapter(...)`) at runtime, which kept calling the adapter db connection even if I didn't want to.

Cloud function invocation get reused by subsequent invocation, so I definitely want to keep the database connection pool until my cloud function is getting offline. As some of my components are shared within multiple cloud functions (My mongodb service for example) it triggers the adapter connection in every cloud function even if they don't need it.

So, I figured out a solution by playing around with your adapter. In case it could useful for someone else, here is what I did :
I created a specific middleware that setup the mongo adapter configuration (which uses my own db connection delegator) and calls the idempotency middleware itself. This custom middleware can then be reused in any endpoint that needs it without triggering the `newAdapter()` default db connection. Instead of using the `newAdapter()` I instantiate a new `MongoAdapter(...) ` directly, then this middleware becomes in charge to call the `.init()` method, so that the connection to the DB is made only when it needs it.

```
import { idempotency } from 'express-idempotency';
import { MongoAdapter } from 'express-idempotency-mongo-adapter';
import { getDb } from '../libs/services/mongodb/mongodb.service';

let dataAdapter: MongoAdapter;

export const idempotencyDefaultAdapter = async (req, res, next) => {
  if (!dataAdapter) {
    dataAdapter = new MongoAdapter({
      useDelegation: true,
      delegate: () => getDb(),
      collectionPrefix: 'idempotency',
      ttl: 86400,
    }) 
  }
  if (!dataAdapter.isInitialized()) {
    await dataAdapter.init();
  }
  await idempotency({ dataAdapter })(req, res, next);
};


```

Feel free to let me know if you have a better recommendation. In any case, thank you very much again for your help !

**Comment by joscelynjean** [comment]
Hi @rodneyrd ,

Nice one. I am happy that you found a solution with what already exists.

It is probably my lack of knowledge of the Google Cloud Function which did not allow me to propose a better solution.

Thank you for sharing your solution. It will be valuable documentation for others.
